server:
  port: 8085
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: axdsw121@gmail.com
    password: cuuljotwyvacynnm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/temp
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:    
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/at?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: ghfkddl1!!
mybatis:
  type-aliases-package: com.sbs.cwy.at.dto
custom:
   siteName: 오디션 트리
   siteMainUri: https://auditiontree.com/
   logoText: 오디션 트리
   emailFrom: no-reply@audiotiontree.com
   emailFromName: 오디션 트리 